# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'views/mercury.ui'
#
# Created: Tue Aug 14 21:33:51 2012
#      by: pyside-uic 0.2.13 running on PySide 1.0.6
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MercuryClass(object):
    def setupUi(self, MercuryClass):
        MercuryClass.setObjectName("MercuryClass")
        MercuryClass.resize(800, 480)
        self.gridLayout_6 = QtGui.QGridLayout(MercuryClass)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(1)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.stackedWidget = QtGui.QStackedWidget(MercuryClass)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(800, 480))
        self.stackedWidget.setAutoFillBackground(False)
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginpage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginpage.sizePolicy().hasHeightForWidth())
        self.loginpage.setSizePolicy(sizePolicy)
        self.loginpage.setMinimumSize(QtCore.QSize(800, 480))
        self.loginpage.setObjectName("loginpage")
        self.gridLayout_5 = QtGui.QGridLayout(self.loginpage)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSpacing(1)
        self.gridLayout.setObjectName("gridLayout")
        self.keyboardStack = QtGui.QStackedWidget(self.loginpage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyboardStack.sizePolicy().hasHeightForWidth())
        self.keyboardStack.setSizePolicy(sizePolicy)
        self.keyboardStack.setMinimumSize(QtCore.QSize(800, 215))
        self.keyboardStack.setFrameShape(QtGui.QFrame.NoFrame)
        self.keyboardStack.setObjectName("keyboardStack")
        self.keyboard = QtGui.QWidget()
        self.keyboard.setObjectName("keyboard")
        self.keyboardStack.addWidget(self.keyboard)
        self.gridLayout.addWidget(self.keyboardStack, 1, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.loginpage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        self.pin = QtGui.QLineEdit(self.loginpage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pin.sizePolicy().hasHeightForWidth())
        self.pin.setSizePolicy(sizePolicy)
        self.pin.setMinimumSize(QtCore.QSize(0, 30))
        self.pin.setEchoMode(QtGui.QLineEdit.Password)
        self.pin.setObjectName("pin")
        self.gridLayout_2.addWidget(self.pin, 1, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.loginpage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Mercury/resources/Arrow_Right_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(85, 85))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 1, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem4, 2, 3, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 4, 3, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 3, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.loginpage)
        self.homePage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homePage.sizePolicy().hasHeightForWidth())
        self.homePage.setSizePolicy(sizePolicy)
        self.homePage.setMinimumSize(QtCore.QSize(800, 480))
        self.homePage.setObjectName("homePage")
        self.gridLayout_16 = QtGui.QGridLayout(self.homePage)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(2)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSpacing(2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.statusLine = QtGui.QLabel(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusLine.sizePolicy().hasHeightForWidth())
        self.statusLine.setSizePolicy(sizePolicy)
        self.statusLine.setMinimumSize(QtCore.QSize(0, 30))
        self.statusLine.setFrameShape(QtGui.QFrame.Box)
        self.statusLine.setFrameShadow(QtGui.QFrame.Sunken)
        self.statusLine.setAlignment(QtCore.Qt.AlignCenter)
        self.statusLine.setObjectName("statusLine")
        self.gridLayout_3.addWidget(self.statusLine, 9, 0, 1, 4)
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.brightnessDown = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessDown.sizePolicy().hasHeightForWidth())
        self.brightnessDown.setSizePolicy(sizePolicy)
        self.brightnessDown.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Mercury/resources/Brightness_Down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brightnessDown.setIcon(icon1)
        self.brightnessDown.setIconSize(QtCore.QSize(64, 64))
        self.brightnessDown.setAutoRepeat(True)
        self.brightnessDown.setAutoRepeatDelay(200)
        self.brightnessDown.setAutoRepeatInterval(50)
        self.brightnessDown.setObjectName("brightnessDown")
        self.gridLayout_12.addWidget(self.brightnessDown, 0, 0, 1, 1)
        self.brightnessUp = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessUp.sizePolicy().hasHeightForWidth())
        self.brightnessUp.setSizePolicy(sizePolicy)
        self.brightnessUp.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Mercury/resources/Brightness_Up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brightnessUp.setIcon(icon2)
        self.brightnessUp.setIconSize(QtCore.QSize(64, 64))
        self.brightnessUp.setAutoRepeat(True)
        self.brightnessUp.setAutoRepeatDelay(200)
        self.brightnessUp.setAutoRepeatInterval(50)
        self.brightnessUp.setObjectName("brightnessUp")
        self.gridLayout_12.addWidget(self.brightnessUp, 0, 1, 1, 1)
        self.quitButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.quitButton.sizePolicy().hasHeightForWidth())
        self.quitButton.setSizePolicy(sizePolicy)
        self.quitButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Mercury/resources/Cancel_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.quitButton.setIcon(icon3)
        self.quitButton.setIconSize(QtCore.QSize(64, 64))
        self.quitButton.setObjectName("quitButton")
        self.gridLayout_12.addWidget(self.quitButton, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_12, 0, 0, 3, 1)
        self.nextPage = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nextPage.sizePolicy().hasHeightForWidth())
        self.nextPage.setSizePolicy(sizePolicy)
        self.nextPage.setText("")
        self.nextPage.setIcon(icon)
        self.nextPage.setIconSize(QtCore.QSize(65, 65))
        self.nextPage.setObjectName("nextPage")
        self.gridLayout_3.addWidget(self.nextPage, 0, 2, 3, 2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.specPageStack = QtGui.QStackedWidget(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.specPageStack.sizePolicy().hasHeightForWidth())
        self.specPageStack.setSizePolicy(sizePolicy)
        self.specPageStack.setMinimumSize(QtCore.QSize(0, 50))
        self.specPageStack.setObjectName("specPageStack")
        self.gridLayout_4.addWidget(self.specPageStack, 2, 0, 1, 1)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setSpacing(2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.inboxButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.inboxButton.sizePolicy().hasHeightForWidth())
        self.inboxButton.setSizePolicy(sizePolicy)
        self.inboxButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Mercury/resources/Inbox_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.inboxButton.setIcon(icon4)
        self.inboxButton.setIconSize(QtCore.QSize(100, 100))
        self.inboxButton.setCheckable(False)
        self.inboxButton.setObjectName("inboxButton")
        self.gridLayout_11.addWidget(self.inboxButton, 2, 1, 1, 1)
        self.outboxButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.outboxButton.sizePolicy().hasHeightForWidth())
        self.outboxButton.setSizePolicy(sizePolicy)
        self.outboxButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Mercury/resources/Outbox_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.outboxButton.setIcon(icon5)
        self.outboxButton.setIconSize(QtCore.QSize(100, 100))
        self.outboxButton.setCheckable(False)
        self.outboxButton.setObjectName("outboxButton")
        self.gridLayout_11.addWidget(self.outboxButton, 2, 3, 1, 1)
        self.composeTextButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.composeTextButton.sizePolicy().hasHeightForWidth())
        self.composeTextButton.setSizePolicy(sizePolicy)
        self.composeTextButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Mercury/resources/New_Message_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.composeTextButton.setIcon(icon6)
        self.composeTextButton.setIconSize(QtCore.QSize(100, 100))
        self.composeTextButton.setCheckable(False)
        self.composeTextButton.setObjectName("composeTextButton")
        self.gridLayout_11.addWidget(self.composeTextButton, 2, 5, 1, 1)
        self.weatherButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.weatherButton.sizePolicy().hasHeightForWidth())
        self.weatherButton.setSizePolicy(sizePolicy)
        self.weatherButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Mercury/resources/Weather_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.weatherButton.setIcon(icon7)
        self.weatherButton.setIconSize(QtCore.QSize(100, 100))
        self.weatherButton.setCheckable(True)
        self.weatherButton.setObjectName("weatherButton")
        self.gridLayout_11.addWidget(self.weatherButton, 2, 7, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 2, 0, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 2, 2, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem10, 2, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem11, 2, 6, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem12, 2, 8, 1, 1)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.panicButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.panicButton.sizePolicy().hasHeightForWidth())
        self.panicButton.setSizePolicy(sizePolicy)
        self.panicButton.setMinimumSize(QtCore.QSize(112, 108))
        self.panicButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/Mercury/resources/Panic_text_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/Mercury/resources/Panic_text_100_high.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.panicButton.setIcon(icon8)
        self.panicButton.setIconSize(QtCore.QSize(100, 100))
        self.panicButton.setCheckable(True)
        self.panicButton.setObjectName("panicButton")
        self.gridLayout_17.addWidget(self.panicButton, 0, 0, 1, 1)
        self.waypointButton = QtGui.QPushButton(self.homePage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.waypointButton.sizePolicy().hasHeightForWidth())
        self.waypointButton.setSizePolicy(sizePolicy)
        self.waypointButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/Mercury/resources/Poll_GPS_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.waypointButton.setIcon(icon9)
        self.waypointButton.setIconSize(QtCore.QSize(100, 100))
        self.waypointButton.setCheckable(True)
        self.waypointButton.setObjectName("waypointButton")
        self.gridLayout_17.addWidget(self.waypointButton, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_17, 0, 0, 1, 9)
        spacerItem13 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem13, 1, 0, 1, 9)
        self.gridLayout_4.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 7, 0, 1, 4)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 0, 1, 3, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 8, 0, 1, 4)
        spacerItem17 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem17, 3, 0, 1, 4)
        self.gridLayout_16.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.homePage)
        self.additionalPage = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.additionalPage.sizePolicy().hasHeightForWidth())
        self.additionalPage.setSizePolicy(sizePolicy)
        self.additionalPage.setMinimumSize(QtCore.QSize(800, 480))
        self.additionalPage.setObjectName("additionalPage")
        self.gridLayout_14 = QtGui.QGridLayout(self.additionalPage)
        self.gridLayout_14.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_14.setSpacing(2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setSpacing(1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_15 = QtGui.QGridLayout()
        self.gridLayout_15.setSpacing(1)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.adminAsset = QtGui.QPushButton(self.additionalPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adminAsset.sizePolicy().hasHeightForWidth())
        self.adminAsset.setSizePolicy(sizePolicy)
        self.adminAsset.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/Mercury/resources/Setup_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adminAsset.setIcon(icon10)
        self.adminAsset.setIconSize(QtCore.QSize(100, 100))
        self.adminAsset.setCheckable(False)
        self.adminAsset.setObjectName("adminAsset")
        self.gridLayout_15.addWidget(self.adminAsset, 0, 4, 1, 1)
        self.defaultContacts = QtGui.QPushButton(self.additionalPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultContacts.sizePolicy().hasHeightForWidth())
        self.defaultContacts.setSizePolicy(sizePolicy)
        self.defaultContacts.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/Mercury/resources/Recipients_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.defaultContacts.setIcon(icon11)
        self.defaultContacts.setIconSize(QtCore.QSize(100, 100))
        self.defaultContacts.setObjectName("defaultContacts")
        self.gridLayout_15.addWidget(self.defaultContacts, 0, 1, 1, 1)
        self.freeFormat = QtGui.QPushButton(self.additionalPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.freeFormat.sizePolicy().hasHeightForWidth())
        self.freeFormat.setSizePolicy(sizePolicy)
        self.freeFormat.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/Mercury/resources/Add_Contacts_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.freeFormat.setIcon(icon12)
        self.freeFormat.setIconSize(QtCore.QSize(100, 100))
        self.freeFormat.setObjectName("freeFormat")
        self.gridLayout_15.addWidget(self.freeFormat, 0, 2, 1, 1)
        self.adminButton = QtGui.QPushButton(self.additionalPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.adminButton.sizePolicy().hasHeightForWidth())
        self.adminButton.setSizePolicy(sizePolicy)
        self.adminButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/Mercury/resources/Admin_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adminButton.setIcon(icon13)
        self.adminButton.setIconSize(QtCore.QSize(100, 100))
        self.adminButton.setCheckable(False)
        self.adminButton.setObjectName("adminButton")
        self.gridLayout_15.addWidget(self.adminButton, 0, 3, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_15, 2, 0, 1, 2)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem18, 1, 0, 1, 2)
        spacerItem19 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem19, 3, 0, 1, 2)
        self.prevPage = QtGui.QPushButton(self.additionalPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prevPage.sizePolicy().hasHeightForWidth())
        self.prevPage.setSizePolicy(sizePolicy)
        self.prevPage.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/Mercury/resources/Arrow_Left_100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevPage.setIcon(icon14)
        self.prevPage.setIconSize(QtCore.QSize(85, 85))
        self.prevPage.setObjectName("prevPage")
        self.gridLayout_13.addWidget(self.prevPage, 4, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayout_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.additionalPage)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.actionExit = QtGui.QAction(MercuryClass)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(MercuryClass)
        self.stackedWidget.setCurrentIndex(1)
        self.keyboardStack.setCurrentIndex(0)
        self.specPageStack.setCurrentIndex(-1)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL("clicked()"), MercuryClass.isLoggedIn)
        QtCore.QObject.connect(self.prevPage, QtCore.SIGNAL("clicked()"), MercuryClass.selectHomePage)
        QtCore.QObject.connect(self.adminButton, QtCore.SIGNAL("clicked()"), MercuryClass.showAdminHome)
        QtCore.QObject.connect(self.adminAsset, QtCore.SIGNAL("clicked()"), MercuryClass.showAssetHome)
        QtCore.QObject.connect(self.composeTextButton, QtCore.SIGNAL("clicked()"), MercuryClass.newMessage)
        QtCore.QObject.connect(self.outboxButton, QtCore.SIGNAL("clicked()"), MercuryClass.showOutbox)
        QtCore.QObject.connect(self.inboxButton, QtCore.SIGNAL("clicked()"), MercuryClass.showInbox)
        QtCore.QObject.connect(self.brightnessDown, QtCore.SIGNAL("clicked()"), MercuryClass.brightnessDown)
        QtCore.QObject.connect(self.brightnessUp, QtCore.SIGNAL("clicked()"), MercuryClass.brightnessUp)
        QtCore.QObject.connect(self.panicButton, QtCore.SIGNAL("clicked()"), MercuryClass.panicClicked)
        QtCore.QObject.connect(self.nextPage, QtCore.SIGNAL("clicked()"), MercuryClass.selectAdditPage)
        QtCore.QObject.connect(self.waypointButton, QtCore.SIGNAL("clicked()"), MercuryClass.buildWaypoint)
        QtCore.QObject.connect(self.weatherButton, QtCore.SIGNAL("clicked()"), MercuryClass.showWeather)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL("clicked()"), MercuryClass.quit)
        QtCore.QObject.connect(self.defaultContacts, QtCore.SIGNAL("clicked()"), MercuryClass.showDefaultRecipients)
        QtCore.QObject.connect(self.freeFormat, QtCore.SIGNAL("clicked()"), MercuryClass.showFreeFormatEditor)
        QtCore.QObject.connect(self.pin, QtCore.SIGNAL("textChanged(QString)"), MercuryClass.pinChanged)
        QtCore.QMetaObject.connectSlotsByName(MercuryClass)

    def retranslateUi(self, MercuryClass):
        MercuryClass.setWindowTitle(QtGui.QApplication.translate("MercuryClass", "Mercury", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MercuryClass", "Admin pin code:", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLine.setStyleSheet(QtGui.QApplication.translate("MercuryClass", "background-color: rgb(200, 200, 200)", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLine.setText(QtGui.QApplication.translate("MercuryClass", "Message Line", None, QtGui.QApplication.UnicodeUTF8))
        self.inboxButton.setStyleSheet(QtGui.QApplication.translate("MercuryClass", "font: 12pt \"MS Shell Dlg 2\";", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MercuryClass", "E&xit", None, QtGui.QApplication.UnicodeUTF8))

import mercury_rc
